name: cPractice
authors:
  - commandf1
version: ${project.version}
main: space.commandf1.practice.cPracticePlugin
softdepend:
  - PlaceholderAPI

loadbefore:
  - PlaceholderAPI

# practice.commands.admin
permissions:
  practice.commands.admin:
    default: not op